name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true
    - name: Azure Blob Storage Upload
      uses: bacongobbler/azure-blob-storage-upload@v1.0.0
      with:
        # The name of the directory you want to upload
        source_dir: dist
        # The name of the storage account container these assets will be uploaded to
        container_name: powerbijs
        # The connection string for the storage account
        connection_string: ${{ secrets.ConnectionString }}
